site_name: Horse
site_description: Horse web framework, an Express inspired web framework for Delphi. Designed to ease things up for fast development in a minimalist way and with high performance.
repo_url: https://github.com/HashLoad/horse
edit_uri: ""
theme:
  icon:
    logo: material/horse
    repo: fontawesome/brands/github
  language: pt
  # languages:
  # - en: /en/
  # - pt: /pt/
  palette:
    primary: deep orange

  name: material
  features:
    - header.autohide
    - search.seggest
    - search.highlight
    - contents.tabs.link

plugins:
  - search
  - i18n:
      default_language: pt
      languages:
        en: English
        pt: Português
      translate_nav:
        en:
          section title: "Section"
          subsection: "Subsection"
          page title: "Page with title translated"
          Guia: "Guide"
          Introdução: "Introduction"
          resources: "Resources"
          middlewares: "Middlewares"
          official-middlewares: "Official Middlewares"
        pt:
          section title: "Seção"
          subsection: "Subseção"
          page title: "Página com título traduzido"
          resources: "Recursos"
          middlewares: "Middlewares"
          official-middlewares: "Middlewares Oficiais"

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
  - footnotes

extra:
  alternate:
    - link: ./en/
      name: English
      lang: en
    - link: ./
      name: Português
      lang: pt
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/hashload
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCl4IApn7H4mZ1V-nmNijL6A
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VBBPhv6m

nav:
  # - Languages:
  # - en: /en/
  # - pt: /pt/
  - index.md
  - index.en.md
  - Introdução:
      - installation.md
      - installation.en.md
      - hello-world.md
      - hello-world.en.md
      - basic-routing.md
      - basic-routing.en.md
  - Guia:
      - "routing.md"
  - resources:
      - middlewares:
          - "middlewares/middlewares.md"
          - official-middlewares:
              - "middlewares/jhonson.md"
              - "middlewares/basic-auth.md"
              - "middlewares/horse-cors.md"
              - "middlewares/octet-stream.md"
              - "middlewares/horse-jwt.md"
              - "middlewares/handle-exception.md"
              - "middlewares/horse-compression.md"
