name: build and deploy mkdocs to github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive" 
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
          
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
          
      - name: Build site Portuguese
        working-directory: ./docs/pt
        run: mkdocs build

      - name: Deploy
        run: cd ..
        run: mkdocs gh-deploy --config-file ../docs/pt/mkdocs.yml --remote-branch master        