name: build and deploy mkdocs to github pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: "recursive"
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Build Site
        run: mkdocs build

      - name: Deploy
        run: mkdocs gh-deploy --force
